openapi: '3.0.3'
info:
  title: Reservations API
  version: '1.0'
servers:
- url: http://localhost:3000/
paths:
  /reservations:
    get:
      summary: Retrieve a list of reservations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'
    post:
      summary: Create a new reservation
      requestBody:
        description: Reservation object to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReservationDto'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'

  /reservations/{id}:
    get:
      summary: Get reservation by ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: Unique reservation ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
        '404':
          description: Reservation not found
    patch:
      summary: Update reservation by ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: Unique reservation ID
      requestBody:
        description: Updated reservation object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateReservationDto'
      responses:
        '200':
          description: Updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
    delete:
      summary: Delete reservation by ID
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: Unique reservation ID
      responses:
        '204':
          description: Deleted successfully

components:
  schemas:
    Reservation:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the reservation
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the reservation
        startDate:
          type: string
          format: date-time
          description: Start date of the reservation
        endDate:
          type: string
          format: date-time
          description: End date of the reservation
        userId:
          type: string
          description: User ID associated with the reservation
        placeId:
          type: string
          description: Place ID associated with the reservation
        invoiceId:
          type: string
          description: Invoice ID for the reservation

    CreateReservationDto:
      type: object
      properties:
        startDate:
          type: string
          format: date-time
          description: Start date for the reservation
        endDate:
          type: string
          format: date-time
          description: End date for the reservation
        placeId:
          type: string
          description: Place ID for the reservation
        invoiceId:
          type: string
          description: Invoice ID for the reservation

    UpdateReservationDto:
      type: object
      properties:
        startDate:
          type: string
          format: date-time
          description: Start date for the reservation
        endDate:
          type: string
          format: date-time
          description: End date for the reservation
        placeId:
          type: string
          description: Place ID for the reservation
        invoiceId:
          type: string
          description: Invoice ID for the reservation
